In [1]:
import numpy as np
import pandas as pd

### Splitting the Dataset

In [2]:
price = pd.read_csv("C:/Users/hp/Desktop/CVT/Datasets-master/homeprices.csv")
price

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [3]:
#Identify input columns and prepare input variable
X = price.iloc[:,0:2]
X

town  area
0   monroe township  2600
1   monroe township  3000
2   monroe township  3200
3   monroe township  3600
4   monroe township  4000
5      west windsor  2600
6      west windsor  2800
7      west windsor  3300
8      west windsor  3600
9       robinsville  2600
10      robinsville  2900
11      robinsville  3100
12      robinsville  3600

In [4]:
#Identify output columns and prepare output variable
y = price.iloc[:,2]
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [5]:
#separate the input into trainig and testing
#separate the output into trainig and testing
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [7]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(10, 2)
(3, 2)
(10,)
(3,)


In [8]:
X_train

town  area
3   monroe township  3600
9       robinsville  2600
6      west windsor  2800
8      west windsor  3600
11      robinsville  3100
1   monroe township  3000
7      west windsor  3300
5      west windsor  2600
2   monroe township  3200
0   monroe township  2600

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 1)

In [10]:
X_train

town  area
10      robinsville  2900
1   monroe township  3000
6      west windsor  2800
0   monroe township  2600
7      west windsor  3300
12      robinsville  3600
9       robinsville  2600
8      west windsor  3600
11      robinsville  3100
5      west windsor  2600

### Feature Scaling

In [11]:
sample = pd.DataFrame({'W.E': [2,4,5,6,7,8], 'Age': [28,25,32,45,33, 32], 
                       'Salary': [300000, 400000, 500000, 600000, 700000, 800000], 
                       'Distance': [10, 12, 23, 32, 15, 17], 
                      'Expected Salary': [400000, 500000, 600000, 700000, 800000, 900000]})
sample

W.E  Age  Salary  Distance  Expected Salary
0    2   28  300000        10           400000
1    4   25  400000        12           500000
2    5   32  500000        23           600000
3    6   45  600000        32           700000
4    7   33  700000        15           800000
5    8   32  800000        17           900000

In [13]:
from sklearn.preprocessing import scale,StandardScaler,MinMaxScaler

In [14]:
scaled_data = scale(sample)
scaled_data

array([[-1.69030851, -0.72134777, -1.46385011, -1.09980534, -1.46385011],
       [-0.6761234 , -1.20224629, -0.87831007, -0.83046526, -0.87831007],
       [-0.16903085, -0.08014975, -0.29277002,  0.6509052 , -0.29277002],
       [ 0.3380617 ,  2.00374382,  0.29277002,  1.86293558,  0.29277002],
       [ 0.84515425,  0.08014975,  0.87831007, -0.42645513,  0.87831007],
       [ 1.35224681, -0.08014975,  1.46385011, -0.15711505,  1.46385011]])

In [15]:
sc = StandardScaler()
sc_data = sc.fit_transform(sample)
sc_data

array([[-1.69030851, -0.72134777, -1.46385011, -1.09980534, -1.46385011],
       [-0.6761234 , -1.20224629, -0.87831007, -0.83046526, -0.87831007],
       [-0.16903085, -0.08014975, -0.29277002,  0.6509052 , -0.29277002],
       [ 0.3380617 ,  2.00374382,  0.29277002,  1.86293558,  0.29277002],
       [ 0.84515425,  0.08014975,  0.87831007, -0.42645513,  0.87831007],
       [ 1.35224681, -0.08014975,  1.46385011, -0.15711505,  1.46385011]])

In [16]:
mms = MinMaxScaler()
mms_data = mms.fit_transform(sample)
mms_data

array([[0.        , 0.15      , 0.        , 0.        , 0.        ],
       [0.33333333, 0.        , 0.2       , 0.09090909, 0.2       ],
       [0.5       , 0.35      , 0.4       , 0.59090909, 0.4       ],
       [0.66666667, 1.        , 0.6       , 1.        , 0.6       ],
       [0.83333333, 0.4       , 0.8       , 0.22727273, 0.8       ],
       [1.        , 0.35      , 1.        , 0.31818182, 1.        ]])

In [20]:
mms_data.mean    

<function ndarray.mean>