In [1]:
import pandas as pd
import numpy as np

In [7]:
dict1 = {'W.E':[2,4,5,6,7,8],
        'Age' : [28,25,32,45,33,32],
        'salary':[30000,40000,50000,60000,70000,80000],
        'distance':[10,12,23,32,15,17],
        'expected_salary':[40000,50000,60000,70000,80000,90000]}

In [8]:
sample = pd.DataFrame(dict1)
sample

W.E  Age  salary  distance  expected_salary
0    2   28   30000        10            40000
1    4   25   40000        12            50000
2    5   32   50000        23            60000
3    6   45   60000        32            70000
4    7   33   70000        15            80000
5    8   32   80000        17            90000

### scale

In [9]:
from sklearn.preprocessing import scale

In [10]:
scaled_data = scale(sample)
scaled_data

array([[-1.69030851, -0.72134777, -1.46385011, -1.09980534, -1.46385011],
       [-0.6761234 , -1.20224629, -0.87831007, -0.83046526, -0.87831007],
       [-0.16903085, -0.08014975, -0.29277002,  0.6509052 , -0.29277002],
       [ 0.3380617 ,  2.00374382,  0.29277002,  1.86293558,  0.29277002],
       [ 0.84515425,  0.08014975,  0.87831007, -0.42645513,  0.87831007],
       [ 1.35224681, -0.08014975,  1.46385011, -0.15711505,  1.46385011]])

In [11]:
scaled_data = pd.DataFrame(scaled_data)
scaled_data

0         1        2         3        4
0 -1.690309 -0.721348 -1.46385 -1.099805 -1.46385
1 -0.676123 -1.202246 -0.87831 -0.830465 -0.87831
2 -0.169031 -0.080150 -0.29277  0.650905 -0.29277
3  0.338062  2.003744  0.29277  1.862936  0.29277
4  0.845154  0.080150  0.87831 -0.426455  0.87831
5  1.352247 -0.080150  1.46385 -0.157115  1.46385

In [12]:
scaled_data.columns = sample.columns

In [13]:
scaled_data

W.E       Age   salary  distance  expected_salary
0 -1.690309 -0.721348 -1.46385 -1.099805         -1.46385
1 -0.676123 -1.202246 -0.87831 -0.830465         -0.87831
2 -0.169031 -0.080150 -0.29277  0.650905         -0.29277
3  0.338062  2.003744  0.29277  1.862936          0.29277
4  0.845154  0.080150  0.87831 -0.426455          0.87831
5  1.352247 -0.080150  1.46385 -0.157115          1.46385

###  StandardScaler

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
df = sample.copy() 

In [16]:
sc = StandardScaler()
df = sc.fit_transform(df)
df

array([[-1.69030851, -0.72134777, -1.46385011, -1.09980534, -1.46385011],
       [-0.6761234 , -1.20224629, -0.87831007, -0.83046526, -0.87831007],
       [-0.16903085, -0.08014975, -0.29277002,  0.6509052 , -0.29277002],
       [ 0.3380617 ,  2.00374382,  0.29277002,  1.86293558,  0.29277002],
       [ 0.84515425,  0.08014975,  0.87831007, -0.42645513,  0.87831007],
       [ 1.35224681, -0.08014975,  1.46385011, -0.15711505,  1.46385011]])

In [17]:
df = pd.DataFrame(df)
df

0         1        2         3        4
0 -1.690309 -0.721348 -1.46385 -1.099805 -1.46385
1 -0.676123 -1.202246 -0.87831 -0.830465 -0.87831
2 -0.169031 -0.080150 -0.29277  0.650905 -0.29277
3  0.338062  2.003744  0.29277  1.862936  0.29277
4  0.845154  0.080150  0.87831 -0.426455  0.87831
5  1.352247 -0.080150  1.46385 -0.157115  1.46385

### Min - Max scaler

In [18]:
from sklearn.preprocessing import MinMaxScaler

In [19]:
df1 = sample.copy()

In [21]:
mms = MinMaxScaler()
df1 = mms.fit_transform(df1)
df1

array([[0.        , 0.15      , 0.        , 0.        , 0.        ],
       [0.33333333, 0.        , 0.2       , 0.09090909, 0.2       ],
       [0.5       , 0.35      , 0.4       , 0.59090909, 0.4       ],
       [0.66666667, 1.        , 0.6       , 1.        , 0.6       ],
       [0.83333333, 0.4       , 0.8       , 0.22727273, 0.8       ],
       [1.        , 0.35      , 1.        , 0.31818182, 1.        ]])

In [22]:
df1 = pd.DataFrame(df1)
df1

0     1    2         3    4
0  0.000000  0.15  0.0  0.000000  0.0
1  0.333333  0.00  0.2  0.090909  0.2
2  0.500000  0.35  0.4  0.590909  0.4
3  0.666667  1.00  0.6  1.000000  0.6
4  0.833333  0.40  0.8  0.227273  0.8
5  1.000000  0.35  1.0  0.318182  1.0

### Outlier detect and removal 