In [1]:
f = open("demo.txt","w")
data = '''Row-1
Row-2
Row-3
Row-4
Row-5'''
f.write(data)
f.close()

In [2]:
f = open("sample.txt","w")
f1 = open("demo.txt","r")
copied_data = f1.read()
f.write(copied_data)
f.close()
f1.close()

### Packages:
1. Numpy ==> n dimentional Arrays
2. Pandas ==> Data Frames and Series
3. Matplotlib
4. seaborn
5. scikit learn

In [3]:
import numpy as np

In [4]:
list1 = list(range(1,11))

In [5]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
arr1 = np.array(list1)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
print(type(list1),type(arr1))

<class 'list'> <class 'numpy.ndarray'>


In [8]:
list1[0]

1

In [9]:
arr1[0]

1

### Difference between Python list and Numpy array
1. less memory
2. Fast
3. convinient

In [15]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
from sys import getsizeof 
getsizeof(list1[0]) * 10

280

In [18]:
arr1.itemsize * arr1.size 

40

In [53]:
import time

size = 100

list1 = list(range(size))
list2 = list(range(size))
start = time.time()
result1 = [list1[i]+list2[i] for i in range(size)]
end = time.time()
print("List addition time:",end-start)

arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
result2 = arr1 + arr2
end = time.time()
print("Array addition time:",end-start)

List addition time: 0.005046844482421875
Array addition time: 0.0


In [55]:
print(result1)
print(result2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]


In [56]:
#1-dimensional array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [58]:
#2-dimensional array
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
a1.shape

(3, 3)

### Slicing

In [60]:
#Accessing elements
print(a[0])

1


In [61]:
print(a1[1,1])

5


In [62]:
print(a1[1,1:3])

[5 6]


In [63]:
print(a1[2])

[7 8 9]


### Iterating through array

In [64]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
for i in a1:
    for j in i:
        print(j,end=" ")

1 2 3 4 5 6 7 8 9 

In [68]:
np.array(a1.flat)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
#flat ==> flattens all the elements of an array
for i in a1.flat:
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 

In [70]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Attributes/properties:
1. size ==> size of the array
2. itemsize ==> single item size
3. ndim ==> dimensions 
4. shape ==> row,cols
5. flat

In [72]:
print(a1.ndim)
print(a.ndim)

2
1


In [73]:
print(a.shape)
print(a1.shape)

(3,)
(3, 3)


In [74]:
print(a.dtype)

int32
