### Appending an array

In [1]:
import numpy as np

In [2]:
a1 = np.array([],dtype="int32")

In [3]:
a1

array([], dtype=int32)

In [6]:
a1 = np.append(a1,[12])

In [7]:
a1

array([12])

In [8]:
a1 = np.append(a1,[13,14,15,16])
a1

array([12, 13, 14, 15, 16])

In [12]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)

In [13]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [16]:
#vstack() ==> vertical stacking
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [17]:
#hstack() ==> horizantal stacking
np.hstack((arr1,arr2))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

### Functions:

In [18]:
#zeros() ==> array with all the elements are zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [19]:
np.zeros((2,2),dtype="int32")

array([[0, 0],
       [0, 0]])

In [21]:
#ones() ==> array with all the elements are ones
np.ones((3,3),dtype="int32")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [22]:
#full() ==> array with all the elements are given value
np.full((2,2),10.5)

array([[10.5, 10.5],
       [10.5, 10.5]])

In [23]:
#eye() ==> gives you an identical array
np.eye(3,dtype="int32")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:
#arange() ==> similar to range
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [26]:
#linspace() ==> linear spacing elements will be return
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [27]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [38]:
#reshape ==> reshaping your array
a = np.arange(1,10)
print(a.shape,a)
a = a.reshape(3,3)
print(a.shape,a)

(9,) [1 2 3 4 5 6 7 8 9]
(3, 3) [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
a1 = np.array(a.flat)
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a2 = np.array(a1.flat)
a2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
#ravel() ==> flattens your array
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.array(a.flat)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Maths related function:

In [45]:
#min(),max()
print(a.min())
print(a.max())

1
9


In [46]:
#sum
print(a.sum())

45


In [48]:
arr1 = np.arange(1,10).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
print(arr1.sum())
print(arr1.sum(axis = 1))#row
print(arr1.sum(axis = 0))#column

45
[ 6 15 24]
[12 15 18]


In [52]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [53]:
np.mean(arr1)

5.0

In [54]:
np.median(arr1)

5.0

In [55]:
#standard deviation
np.std(arr1)

2.581988897471611

### Mathematical operations

In [56]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)

In [57]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
#dot()  ==> matrix multiplication ==> 3X3 3X3
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [59]:
#Transpose of a matrix
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])