#### Why use pandas in Python?
Pandas has been one of the most commonly used tools for Data Science and Machine learning, which is used for data cleaning and analysis. Here, Pandas is the best tool for handling this real-world messy data.

#### What is the difference between pandas and NumPy?
The Pandas module mainly works with the tabular data, whereas the NumPy module works with the numerical data. The Pandas provides some sets of powerful tools like DataFrame and Series that mainly used for analyzing the data, whereas in NumPy module offers a powerful object called Array.

In [3]:
import numpy as np
list1=list(range(1,11))
arr=np.array(list1).reshape(2,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
list1 = [[ 1,  2,  3,  4,  5],[ 6,  7,  8,  9, 10]]
arr1 = np.array(list1)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
list1

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [7]:
print(list1)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


### Indexing with boolean array

In [8]:
arr1 = np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [9]:
result = (arr1 % 2 == 0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [10]:
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Applying user-defined function

In [11]:
list1 = list(range(1,21))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [13]:
l = [i/(i+1) for i in list1]
print(l)

[0.5, 0.6666666666666666, 0.75, 0.8, 0.8333333333333334, 0.8571428571428571, 0.875, 0.8888888888888888, 0.9, 0.9090909090909091, 0.9166666666666666, 0.9230769230769231, 0.9285714285714286, 0.9333333333333333, 0.9375, 0.9411764705882353, 0.9444444444444444, 0.9473684210526315, 0.95, 0.9523809523809523]


In [14]:
#vectorize() ==> function object
arr = np.array(list1)
f = np.vectorize(lambda x : x/(x+1))
f(arr)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      , 0.95238095])

In [15]:
#3-dimensional array
l = [[[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]]
l

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

In [16]:
a = np.array(l)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
a.shape

(2, 2, 3)

In [18]:
a.ndim

3

### random sub package

In [19]:
from numpy import random 

In [39]:
print(random.randint(1,100))#int value with in the given range
print(random.rand())#float value b/w 0-1

91
0.6715908348433572


In [45]:
#2-d array
print(random.randint(100,size=(3,3)))

[[63 81 13]
 [77 92 86]
 [66 44 11]]


In [46]:
#3-d array
print(random.randint(100,size=(3,3,2)))

[[[60 36]
  [51 35]
  [28 64]]

 [[ 6 18]
  [ 6  5]
  [67 28]]

 [[22 66]
  [76 72]
  [20 32]]]


In [48]:
print(random.rand())
print(random.rand(3))
print(random.rand(3,4))
print(random.rand(2,2,2))

0.45651132451173004
[0.84148247 0.33420739 0.72840034]
[[0.43704536 0.00301494 0.55930991 0.56374136]
 [0.59458652 0.24787614 0.57190315 0.66863233]
 [0.14300056 0.70332002 0.98353068 0.84626774]]
[[[0.64507466 0.75093479]
  [0.74592995 0.6771726 ]]

 [[0.51304947 0.04023267]
  [0.8613061  0.18372287]]]


In [49]:
a = random.randint(100,size=(3,3))
a

array([[83, 46, 83],
       [36,  4, 51],
       [39, 18, 67]])

In [50]:
a

array([[83, 46, 83],
       [36,  4, 51],
       [39, 18, 67]])

In [60]:
random.choice(a.flat)

18

In [72]:
#[1,2,3,4,5],(4,4)
random.choice([1,2,3,4,5],size=(4,4))

array([[3, 3, 4, 2],
       [5, 1, 4, 1],
       [3, 4, 5, 2],
       [5, 3, 1, 2]])

In [73]:
#Accepting values using input()
a1 = np.array([],dtype = "int32")

In [74]:
a1

array([], dtype=int32)

In [76]:
for i in range(1,6):
    a1 = np.append(a1,int(input("Enter a value")))
print(a1)

Enter a value12
Enter a value12
Enter a value23
Enter a value34
Enter a value45
[12 12 12 23 34 45]


In [77]:
#Free 
import pandas as pd

### DataFrame ==> Rows and columns
1. Using 2 dictionaries
2. simple dictionary
3. using Series

In [83]:
dict1 = {"a":1,"b":2,"c":3,"d":4,"e":5,"f":10}
dict2 = {"a":5,"b":6,"c":7,"d":8,"e":9,"h":11}
data = {"First":dict1,"second":dict2}

In [84]:
df = pd.DataFrame(data)
df

First  second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     9.0
f   10.0     NaN
h    NaN    11.0